
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    
    image: web:1.0.0
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./app
          target: /usr/src/app
          ignore:
            - venv/
        - action: rebuild
          path: ./app/requirements.txt
        - action: rebuild
          path: ./app/entrypoint.shop
    restart: unless-stopped
    env_file:
      - ./app/.env
    depends_on:
      - db
  db:
    container_name: homebook_db
    image: postgres:18.0-alpine
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/18/docker/
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Kyiv
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  rabbit_mq:
    image: rabbitmq:4.2-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: celery:1.0.0
    container_name: celery
    command: celery -A config worker -l info
    env_file:
      - ./app/.env
    develop:
      watch:
        - action: sync
          path: ./app
          target: /usr/src/app
          ignore:
            - venv/
        - action: rebuild
          path: ./app/requirements.txt
        - action: rebuild
          path: ./app/entrypoint.shop
    depends_on:
      - rabbit_mq
  dbbrowser:
    image: adminer
    container_name: adminer
    ports:
      - 8082:8080
    depends_on:
      - db
