
services:
  db:
    container_name: homebook_db
    image: postgres:18.0-alpine
    restart: always
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/18/docker/
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Kyiv
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  rabbit_mq:
    image: rabbitmq:4.2-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: celery:1.0.0
    container_name: celery
    command: celery -A homebook worker -l info
    env_file:
      - ./app/.env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit_mq:5672
      - DATABASE_HOST=db
      - MAILDEV_WEB_HOST=maildev
      - MAILDEV_WEB_PORT=1025
    depends_on:
      - rabbit_mq
